using System;
using System.Collections;
using System.IO;
using UnityEngine;
using UnityEngine.UIElements;

// Startup / title screen: the first thing a standalone tester sees, before they control the stand.
//
// It is a second card on StandaloneSessionMenu (not a second menu), so it shares that menu's pause, input
// isolation and restore logic. It only routes to actions that already exist:
//   Start New Scenario -> enters the fresh Scenario One the scene generated before this screen opened
//   Continue           -> ForestSaveController.CanLoad (offer) and Load (act): the existing validated save path
//   Controls / Help    -> a short key list, then back to this screen
//   Quit               -> StandaloneSessionMenu.Quit, the existing quit path
// F10 keeps opening the fuller session card once the player is in the stand.
//
// It deliberately says nothing about ecology or what to do in the forest. Teaching starts in the stand.
//
// Player vs Editor: a standalone Player always opens on this screen (Bootstrap in StandaloneSessionMenu.cs).
// Editor Play Mode enters the stand directly as before, so development and the verification gates do not have
// to click through it; set CCF_STARTUP_SCREEN=1 to exercise the real screen in the Editor.
public sealed partial class StandaloneSessionMenu
{
    // How long to wait for the scene's player, save controller and forest UI before giving up (about 10 s).
    private const int StartupOpenTimeoutFrames = 600;

    public const string StartupTitle = "CCF";
    public const string StartupScenarioName = "Scenario One";
    // Must read as the tail of the scenario definition's display name; StartupScreenVerification checks that.
    public const string StartupScenarioSubtitle = "Sitka Plantation to Continuous-Cover Forest";

    private static readonly Color StartupInk = new Color(0.93f, 0.94f, 0.89f);
    private static readonly Color StartupInkMuted = new Color(0.69f, 0.75f, 0.66f);
    private static readonly Color StartupInkFaint = new Color(0.60f, 0.66f, 0.57f);
    private static readonly Color StartupKey = new Color(0.91f, 0.81f, 0.47f);

    // Keys a first-time tester needs to enter and control the stand. Not a tutorial: the in-game Help (F1) and
    // Learning objectives (O) teach once the player is in the stand.
    private static readonly string[][] ControlRows =
    {
        new[] { "W A S D", "Walk. Hold Shift to run, Space to jump" },
        new[] { "Mouse", "Look around. Esc frees the mouse; click to take it back" },
        new[] { "E", "Inspect the tree or object you are looking at" },
        new[] { "M", "Stand Map" },
        new[] { "Tab", "Work Plan" },
        new[] { "O", "Learning objectives" },
        new[] { "F1", "Help for the screen you are on" },
        new[] { "Esc", "Free the mouse, or close the open panel" },
        new[] { "F5 / F9", "Save / Load" },
        new[] { "F10", "Session menu: new scenario, save, load, quit" },
    };

    // True from bootstrap until the player leaves the title screen. While true, F10 does nothing.
    private bool startupScreen;
    private bool continueChecked, continueAvailable;
    private string continueNote;

    public bool StartupScreenActive => startupScreen;

    // Whether Continue is offered, and the one-line reason when it is not. Valid once the screen has opened.
    public bool ContinueAvailable => continueAvailable;
    public string ContinueNote => continueNote;

    // Make this menu open on the startup screen instead of the F10 session card. Bootstrap calls it straight
    // after adding the component, before Start() runs; a test may call it on a menu that has already started.
    public void ShowStartupScreen()
    {
        if (IsOpen) return;
        startupScreen = true;
        if (document != null) Open();
    }

    // The scene creates the player, save controller and forest UI in their own Start(), so Open() may need
    // more than the two frames Start() already waited.
    private IEnumerator OpenStartupWhenReady()
    {
        for (int frame = 0; !IsOpen && frame < StartupOpenTimeoutFrames; frame++)
        {
            Open();
            if (!IsOpen) yield return null;
        }
        if (IsOpen) yield break;
        // Nothing to guard (a scene other than ForestTest): never leave a blank backdrop over the game.
        startupScreen = false;
        document.rootVisualElement.style.display = DisplayStyle.None;
        Debug.LogWarning("CCF_STARTUP_SCREEN_UNAVAILABLE the scene has no player, save controller and Scenario One UI; continuing without a startup screen");
    }

    // Scenario One is generated by the scene under the new-game policy (StandGeometryPolicy and the current model
    // stack) before this screen opens, and time has been paused since, so "fresh" is decided there, not here.
    // This only hands the stand to the player. It must not rebuild the world or restate any policy value.
    public void StartNewScenario()
    {
        if (!IsOpen || !startupScreen) return;
        ForestEcologyController ecology = FindFirstObjectByType<ForestEcologyController>();
        Close();
        Debug.Log("CCF_STARTUP_NEW_SCENARIO geometry=" + (ecology != null ? StandGeometryModel.Label(ecology.StandGeometryModelVersion) : "unknown")
            + " year=" + (ecology != null ? ecology.EcologicalYear : -1));
    }

    // Loads through the existing validated path, in the same order the F10 menu's own load button uses: give
    // the forest its input back, then Load(). The save is checked again here because the file may have changed
    // since the screen opened; when it no longer loads, nothing is touched and the reason is shown instead.
    public void ContinueSavedForest()
    {
        if (!IsOpen || !startupScreen) return;
        string problem = null;
        if (saves == null || !saves.CanLoad(out problem))
        {
            continueChecked = true;
            continueAvailable = false;
            continueNote = problem ?? "Saving is not available in this scene.";
            StartupCard();
            return;
        }
        Close();
        saves.Load();
        Debug.Log("CCF_STARTUP_CONTINUE");
    }

    public void ShowControlsHelp()
    {
        if (!IsOpen || !startupScreen) return;
        ControlsHelpCard();
    }

    // CanLoad reads and validates the whole save file, so do it once per time the screen is open.
    private void RefreshContinueState()
    {
        if (continueChecked) return;
        continueChecked = true;
        if (saves == null)
        {
            continueAvailable = false;
            continueNote = "Saving is not available in this scene.";
        }
        else
            continueAvailable = saves.CanLoad(out continueNote);
        Debug.Log("CCF_STARTUP_SCREEN_OPEN continueAvailable=" + continueAvailable + (continueAvailable ? "" : " reason=\"" + continueNote + "\""));
    }

    private void StartupCard()
    {
        card.Clear();
        VisualElement column = StartupColumn();
        StartupLabel(column, StartupTitle, 64, StartupInk, true, 2);
        StartupLabel(column, StartupScenarioName, 34, StartupInk, true, 4);
        StartupLabel(column, StartupScenarioSubtitle, 22, StartupInkMuted, false, 40);

        Button start = StartupButton(column, "Start New Scenario", StartNewScenarioClicked, true);
        RefreshContinueState();
        Button continueButton = StartupButton(column, "Continue", ContinueSavedForest, false);
        continueButton.SetEnabled(continueAvailable);
        if (!continueAvailable)
            StartupLabel(column, continueNote, 16, StartupInkMuted, false, 10);
        StartupButton(column, "Controls / Help", ControlsHelpCard, false);
        StartupButton(column, "Quit", Quit, false);

        Label build = StartupLabel(column, "Private test build · " + identity.buildId, 15, StartupInkFaint, false, 0);
        build.style.marginTop = 28;
        FocusWhenReady(continueAvailable ? continueButton : start);
    }

    // Starting new never deletes a save, but F5 later would silently replace it, so say so before the choice.
    private void StartNewScenarioClicked()
    {
        if (!File.Exists(SavePath))
        {
            StartNewScenario();
            return;
        }
        card.Clear();
        VisualElement column = StartupColumn();
        StartupLabel(column, "Start a new Scenario One?", 32, StartupInk, true, 14);
        StartupLabel(column, "You will begin a fresh forest. Your saved forest stays on this device until you save over it (F5, or Save in the F10 menu).",
            20, StartupInkMuted, false, 30);
        Button confirm = StartupButton(column, "Start New Scenario", StartNewScenario, true);
        StartupButton(column, "Back", StartupCard, false);
        FocusWhenReady(confirm);
    }

    private void ControlsHelpCard()
    {
        card.Clear();
        VisualElement column = StartupColumn();
        StartupLabel(column, "Controls", 34, StartupInk, true, 18);
        var list = new ScrollView(ScrollViewMode.Vertical);
        list.style.maxHeight = 440;
        list.style.alignSelf = Align.Stretch;
        list.style.marginBottom = 18;
        column.Add(list);
        foreach (string[] row in ControlRows)
        {
            var line = new VisualElement();
            line.style.flexDirection = FlexDirection.Row;
            line.style.marginBottom = 6;
            Label key = new Label(row[0]);
            key.style.width = 140;
            key.style.flexShrink = 0;
            key.style.fontSize = 20;
            key.style.unityFontStyleAndWeight = FontStyle.Bold;
            key.style.color = StartupKey;
            Label what = new Label(row[1]);
            what.style.flexShrink = 1;
            what.style.flexGrow = 1;
            what.style.fontSize = 20;
            what.style.whiteSpace = WhiteSpace.Normal;
            what.style.color = StartupInk;
            line.Add(key);
            line.Add(what);
            list.Add(line);
        }
        Button back = StartupButton(column, "Back", StartupCard, true);
        FocusWhenReady(back);
    }

    private VisualElement StartupColumn()
    {
        var column = new VisualElement();
        column.style.alignItems = Align.Center;
        card.Add(column);
        return column;
    }

    private static Label StartupLabel(VisualElement parent, string text, int size, Color color, bool bold, float marginBottom)
    {
        var label = new Label(text);
        label.style.fontSize = size;
        label.style.color = color;
        label.style.whiteSpace = WhiteSpace.Normal;
        label.style.unityTextAlign = TextAnchor.MiddleCenter;
        label.style.marginBottom = marginBottom;
        if (bold) label.style.unityFontStyleAndWeight = FontStyle.Bold;
        parent.Add(label);
        return label;
    }

    // Uses the in-game button classes for a consistent look. Unlike the in-game UiKit buttons these stay
    // keyboard-focusable, so Tab / arrows / Enter work on this screen; gameplay keys are blocked while it is open.
    private static Button StartupButton(VisualElement parent, string text, Action action, bool primary)
    {
        var button = new Button(action) { text = text };
        button.AddToClassList("btn");
        if (primary) button.AddToClassList("btn-primary");
        button.style.width = 360;
        button.style.height = 48;
        button.style.fontSize = 22;
        button.style.marginLeft = 0;
        button.style.marginRight = 0;
        button.style.marginBottom = 10;
        parent.Add(button);
        return button;
    }

    // Focus needs the element to be laid out in the panel, so ask on the next layout pass.
    private static void FocusWhenReady(Button button) => button.schedule.Execute(() => button.Focus());
}
